#!/bin/bash
function install_docker_compose {
    echo "-------------------------Installing docker compose---------------------------------
   
   # install compose
   superuser_do 'curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose'
   superuser_do "chmod +x /usr/local/bin/docker-compose"
   superuser_do "ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose"
}
