#!/bin/bash
function install_docker {
    echo "-------------------------Installing ROS---------------------------------"
    superuser_do "apt-get update"
    
    superuser_do "apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common"
    
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | superuser_do "apt-key add -"
    
    superuser_do 'add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"'
   
   superuser_do "apt-get update"
   
   superuser_do "apt-get install docker-ce docker-ce-cli containerd.io"
   
   superuser_do "usermod -aG docker ${USER}"
   
   # install compose
   superuser_do 'curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
   superuser_do "chmod +x /usr/local/bin/docker-compose"
   superuser_do "ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose"
}
