#!/bin/bash
function install_vscode {
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    superuser_do "install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/"
    superuser_do "rm microsoft.gpg"
    superuser_do 'sh -c "echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list"'
    
    superuser_do "apt-get install -y apt-transport-https"
    superuser_do "apt-get update"
    superuser_do "apt-get install -y code" # or code-insiders
}
